version: '3.1'
services:

  unity_room1:
    build:
      context: unity/
    image: unity:latest
    restart: unless-stopped
    ports:
      - "7777:7777/udp"
    networks:
      - web

  unity_room2:
    build:
      context: unity/
    image: unity:latest
    restart: unless-stopped
    ports:
      - "7778:7777/udp"
    networks:
      - web

networks:
  web:
    driver: bridge
